### ISSUE TITLE
Make the show dialog as a separate component

### ISSUE THREAD

**Issue by TarekAlabd** [TarekAlabd/flutter-ecommerce-live-coding#13]
We need to refactor the dialogs in the whole app
So we need to create one component of the dialogue and use it at any place need it.

**Comment by esraamostfa** [comment]
there is no available option to assign the issue to myself, I think this option is available just for the owner and contributors.

**Comment by TarekAlabd** [comment]
This issue is solved and merged!
Great job, @esraamostfa

**Comment by esraamostfa** [comment]
> This issue is solved and merged! Great job, @esraamostfa

Thank you.
